### ISSUE TITLE
Error when loading Etherpad from a subdirectory

### ISSUE THREAD

**Issue by meepmeep** [rhansen/ep_adminpads2#13]
I just updated adminpads2 to 2.1.0 on my freshly updated etherpad-lite (1.8.6), and I get this error message when I try to reach the "manage pads" page :

`Cannot GET /admin/pads `

I'm running etherpad on a subdirectory (domain.tld/pad/), so "/admin/pads" is indeed an incorrect address (should be /pad/admins/pads)
It was working great with previous version, something has changed on the handling of the base URL.

**Comment by rhansen** [comment]
When you visit `/pad/admin/`, what does the page source look like? (right click then click View page source)

**Comment by meepmeep** [comment]
looks like it works after a restart. 

Sorry for this false positive issue !
