### ISSUE TITLE
locales folder

### ISSUE THREAD

**Issue by ovari** [rhansen/ep_adminpads2#2]
Could you please advise where the `locales` folder is so that we can add the `hu` (Hungarian - magyar) translation?

Thank you

**Comment by rhansen** [comment]
That's a very good question. I will do some research to figure out how localization works.

**Comment by rhansen** [comment]
I found https://etherpad.org/doc/v1.8.4/#index_localizing_plugins. So far I haven't had any luck getting it to work for the static HTML file. You can see my work in progress on the [`l10n` branch](https://github.com/rhansen/ep_adminpads2/tree/l10n). You can try it yourself by running the following in your etherpad-lite directory:
```shell
npm install rhansen/ep_adminpads2#l10n
```

If you (or anyone else) knows what I'm doing wrong, please let me know.

**Comment by ovari** [comment]
@JohnMcLear can you please help with https://github.com/rhansen/ep_adminpads2/issues/2#issuecomment-674637875? Thank you

**Comment by JohnMcLear** [comment]
Best thing to do is look at how other plugins have implemented it.  I'm not working on Etherpad at the moment due to other commitments, sorry!

**Comment by rhansen** [comment]
I figured out what was wrong and merged some localization changes. Feel free to open a pull request that adds `locales/hu.json`.
