### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by ovari** [rhansen/ep_adminpads2#5]
> This is a fork of ep_adminpads2, which appears to be no longer maintained.

https://github.com/RpNation/ep_adminpads3#administrate-etherpads

**Comment by rhansen** [comment]
Yes, I do intend to maintain this. I am going to review the changes pushed to ep_adminpads3 and merge them in.

I gave @MShultz access to this GitHub repository, and I gave [rpnation](https://www.npmjs.com/~rpnation) access to the [ep_adminpads2 npm package](https://www.npmjs.com/package/ep_adminpads2).

**Comment by rhansen** [comment]
All relevant changes from ep_adminpads3 have been merged in, so I'm closing this.

@MShultz: Would you mind unpublishing ep_adminpads3 so that users don't get confused?

**Comment by MShultz** [comment]
@rhansen  Sorry for the delay on this. ep_adminpads3 has been unpublished.
